version: "3.8"

networks:
  test-task_network:
    driver: bridge

volumes:
  postgres-data:

services:
  postgres:
    container_name: test-task_pg
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test-task
    volumes:
      - postgres-data:/var/lib/postgresql/test-task/data
    ports:
      - "5449:5432"
    networks:
      - test-task_network
    restart: unless-stopped
